version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y install jq
      - export server_url="kvdemo.$(cat persistent-resources-parameters.json | jq .Parameters.ELBHostedZoneName --raw-output)"
      - ./key_value_test.sh

